// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MIgrationTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "MIgrationTools.727fc32e-eb9a-4930-9510-bfab2c766cad";
        public const string Name = "Migration Tools";
        public const string Description = @"Integrate Entity Framework Migration Tool To Visual Studio With Auto Context Select";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Ahmed Seada";
        public const string Tags = "EF Core";
    }
}
